version: '3.8'

services:
  # Definición del servicio para la base de datos PostgreSQL
  testdb:
    image: postgres:15.1-alpine
    container_name: testdb2
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: postgres
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  pruebamct:
    #build:
      #context: .
      #dockerfile: Dockerfile
    image: ghcr.io/forte-gestorjobs/micro-cloud-tareas:latest
    environment:
      MCT_DBHOST: testdb
      MCT_DBNAME: ${MCT_DBNAME}
      MCT_DBPORT: 5432 
      MCT_DBPWD: ${MCT_DBPWD}
      MCT_DBUSER: ${MCT_DBUSER}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      AWS_REGION: ${AWS_REGION}
    ports:
      - "8082:8082"
    depends_on:
      - testdb
    volumes:
      - /tmp
    restart: unless-stopped

volumes:
  pgdata: